[tool.poetry]
name = "s3-bench"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">= 3.7"
boto3 = "^1.26.99"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
